from django.http import JsonResponse
from django.urls import path

from .api_views import (
    AdminAcademicOverviewApiView,
    AdminDashboardApiView,
    AdminTransportCarDetailApiView,
    DashboardEmploiDuTempsDetailApiView,
    DashboardEmploiDuTempsListCreateApiView,
    DashboardPromotionDetailApiView,
    DashboardPromotionListCreateApiView,
    AdminTransportCarApiView,
    AdminTransportCommuneApiView,
    AdminTransportDepotApiView,
    AdminTransportDriverApiView,
    AdminTransportOverviewApiView,
    AdminTransportRouteApiView,
    DriverTripApiView,
    AdminEnseignantDetailApiView,
    AdminEnseignantListCreateApiView,
    AdminLegacyStudentDetailApiView,
    AdminPortalStudentDetailApiView,
    AdminStudentListApiView,
    AdminStudentOptionsApiView,
    MeTransportCarDetailApiView,
    MeTransportCarsApiView,
    MeDashboardApiView,
    MeDocumentsApiView,
    MeEdtApiView,
    MeForumApiView,
    MeNotesApiView,
    MeProfileApiView,
    MeTransportOverviewApiView,
    MeTransportPaymentsApiView,
)


def health(request):
    return JsonResponse({"app": "scolarite", "status": "ok"})


urlpatterns = [
    path("health/", health, name="scolarite_health"),
    path("me/", MeProfileApiView.as_view(), name="student_me"),
    path("me/dashboard/", MeDashboardApiView.as_view(), name="student_dashboard"),
    path("me/notes/", MeNotesApiView.as_view(), name="student_notes"),
    path("me/edt/", MeEdtApiView.as_view(), name="student_edt"),
    path("me/documents/", MeDocumentsApiView.as_view(), name="student_documents"),
    path("me/forum/", MeForumApiView.as_view(), name="student_forum"),
    path("me/transport/", MeTransportOverviewApiView.as_view(), name="student_transport_overview"),
    path("me/transport/cars/", MeTransportCarsApiView.as_view(), name="student_transport_cars"),
    path("me/transport/cars/<int:pk>/", MeTransportCarDetailApiView.as_view(), name="student_transport_car_detail"),
    path("me/transport/payments/", MeTransportPaymentsApiView.as_view(), name="student_transport_payments"),
    path("transport/driver/trips/", DriverTripApiView.as_view(), name="driver_transport_trips"),
    path("dashboard/", AdminDashboardApiView.as_view(), name="admin_dashboard"),
    path("promotions/", DashboardPromotionListCreateApiView.as_view(), name="dashboard_promotions"),
    path("promotions/<int:pk>/", DashboardPromotionDetailApiView.as_view(), name="dashboard_promotions_detail"),
    path("emploi-du-temps/", DashboardEmploiDuTempsListCreateApiView.as_view(), name="dashboard_schedule"),
    path("emploi-du-temps/<int:pk>/", DashboardEmploiDuTempsDetailApiView.as_view(), name="dashboard_schedule_detail"),
    path("admin/etudiants/", AdminStudentListApiView.as_view(), name="admin_students"),
    path("admin/etudiants/options/", AdminStudentOptionsApiView.as_view(), name="admin_students_options"),
    path("admin/etudiants/<int:pk>/", AdminPortalStudentDetailApiView.as_view(), name="admin_students_detail"),
    path(
        "admin/etudiants/legacy/<str:matricule>/",
        AdminLegacyStudentDetailApiView.as_view(),
        name="admin_students_legacy_detail",
    ),
    path("admin/scolarite/", AdminAcademicOverviewApiView.as_view(), name="admin_scolarite"),
    path("admin/transport/", AdminTransportOverviewApiView.as_view(), name="admin_transport"),
    path("admin/transport/depots/", AdminTransportDepotApiView.as_view(), name="admin_transport_depots"),
    path("admin/transport/communes/", AdminTransportCommuneApiView.as_view(), name="admin_transport_communes"),
    path("admin/transport/routes/", AdminTransportRouteApiView.as_view(), name="admin_transport_routes"),
    path("admin/transport/cars/", AdminTransportCarApiView.as_view(), name="admin_transport_cars"),
    path("admin/transport/cars/<int:pk>/", AdminTransportCarDetailApiView.as_view(), name="admin_transport_cars_detail"),
    path("admin/transport/drivers/", AdminTransportDriverApiView.as_view(), name="admin_transport_drivers"),
    path("admin/enseignants/", AdminEnseignantListCreateApiView.as_view(), name="admin_teachers"),
    path("admin/enseignants/<int:pk>/", AdminEnseignantDetailApiView.as_view(), name="admin_teachers_detail"),
]
